-- ALTER TABLE tww_od.file
--   ALTER COLUMN identifier TYPE character varying(60);
-- will need adaption in matching on INTERLIS Export VSA-KEK 2020
-- VSA-DSS 2020 model adaption implemented with identifier (120)