version: '3'
services:
  db:
    build:
      context: ../
      dockerfile: ./datamodel/.docker/Dockerfile
    image: teksi/tww:${DOCKER_TAG:-unstable}
    working_dir: /src
    volumes:
      - ./datamodel:/src
    ports:
      # making the postgres database accessible for debugging
      - ${TWW_PG_PORT:-5432}:${TWW_PG_PORT:-5432}

  qgis:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION}
    tty: true
    volumes:
      - ${GITHUB_WORKSPACE}:/usr/src
    depends_on:
      - db
