version: '3'
services:
  db:
    build:
      context: ../
      dockerfile: ./datamodel/.docker/Dockerfile
    image: teksi/tww:${DOCKER_TAG:-unstable}
    working_dir: /src
    volumes:
      - ./datamodel:/src
    ports:
      - 5432:5432

  qgis:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION}
    tty: true
    volumes:
      - ${GITHUB_WORKSPACE}:/usr/src
    links:
      - db
