from __future__ import annotations

import argparse
import logging
from pathlib import Path

from teksi_hooks.hook import (
    HookContext,
    HookHandler,
)
from teksi_hooks.capabilities.connection import (
    DatabaseConnectionFactory,
)

from teksi_wastewater.interlis import (
    config,
)
from teksi_wastewater.hooks.adapters.tww_change_object_provider_factory import (
    TwwChangeObjectProviderFactory,
)
from teksi_wastewater.hooks.adapters.tww_quarantine_effect_projector import (
    TwwQuarantineEffectProjector,
)
from teksi_wastewater.hooks.adapters.tww_rights_evaluator_factory import (
    TwwRightsEvaluatorFactory,
)
from teksi_wastewater.hooks.services.tww_change_creation_service import (
    ChangeObjectProviderFactory,
    QuarantineEffectProjector,
    RightsEvaluatorFactory,
)


from teksi_wastewater.hooks.cli import helpers

logger = logging.getLogger(
    __name__,
)



def main() -> int:
    """
    Run the TWW diff-review hook from the command line.
    """

    parser = argparse.ArgumentParser(
        description="Create a tww_diff review job from an XTF file.",
    )

    parser.add_argument(
        "--job-id",
        default=None,
        help=(
            "Optional stable identifier for the tww_diff job. "
            "A UUID is generated by the hook when omitted."
        ),
    )

    parser.add_argument(
        "--job-mode",
        choices=(
            "create",
            "replace",
            "refresh",
        ),
        default="create",
        help=(
            "How to handle an existing tww_diff job with the same job ID."
        ),
    )

    parser.add_argument(
        "--xtf-input",
        required=True,
        type=Path,
        help="Path to the main XTF file to import.",
    )

    parser.add_argument(
        "--provider-oid",
        required=True,
        help="Provider organisation OID used for rights evaluation.",
    )

    parser.add_argument(
        "--dataowner-oid",
        required=True,
        help="Data owner organisation OID used for rights evaluation.",
    )

    # parser.add_argument(
    #     "--import-schema",
    #     default=config.IMPORT_SCHEMA,
    #     help="Quarantine schema used for the import.",
    # )

    # parser.add_argument(
    #     "--live-schema",
    #     default=config.TWW_OD_SCHEMA,
    #     help="Canonical live schema used for comparison and rights evaluation.",
    # )

    parser.add_argument(
        "--orgs-path",
        type=Path,
        default=None,
        help="Optional organisation/reference XTF.",
    )

    parser.add_argument(
        "--incremental_xtf",
        type=Path,
        default=None,
        help="Optional XTF for incremental adaptation, i.e. for AG-XX mappings.",
    )
    # parser.add_argument(
    #     "--incremental_import-schema",
    #     default=config.IMPORT_SCHEMA_INCR,
    #     help="Optional Quarantine schema used for the incremental import.",
    # )

    parser.add_argument(
        "--rights-profile",
        default="default",
        help=(
            "Rights-profile directory name below the hook configuration "
            "directory."
        ),
    )

    parser.add_argument(
        "--hook-config-dir",
        type=Path,
        default=None,
        help=(
            "Directory containing rights-profile subdirectories. "
            "When omitted, the hook may use TWW_DIFF_CONF_DIR."
        ),
    )

    parser.add_argument(
        "--skip_rights_evaluation",
        action="store_true",
        help=(
            "Skip rights evaluation for import. This setting "
            "should only be used when setting a baseline."
        ),
    )

    helpers.add_postgres_connection_args(
            parser,
        )


    args = parser.parse_args()

    parameters = {
        "job_mode": args.job_mode,
        "xtf_input": args.xtf_input,
        "provider_oid": args.provider_oid,
        "dataowner_oid": args.dataowner_oid,
        "import_schema": config.IMPORT_SCHEMA,
        "live_schema": config.TWW_OD_SCHEMA,
        "orgs_path": args.orgs_path,
        "incremental_xtf": args.incremental_xtf,
        "incremental_import_schema": config.IMPORT_SCHEMA_INCR,
        "rights_profile": args.rights_profile,
        "hook_config_dir": args.hook_config_dir,
        "skip_rights_evaluation": args.skip_rights_evaluation,
    }

    if args.job_id is not None:
        parameters["job_id"] = args.job_id

    connection_factory = (
        helpers.database_connection_factory(
            args,
        )
    )

    connection_factory.apply_to_database_config()

    context = HookContext(
        parameters=parameters,
        logger=logger,
        capabilities={
            QuarantineEffectProjector: TwwQuarantineEffectProjector(),
            RightsEvaluatorFactory: TwwRightsEvaluatorFactory(),
            ChangeObjectProviderFactory: TwwChangeObjectProviderFactory(),
            DatabaseConnectionFactory: connection_factory,
        },
    )

    hook_file = (
        Path(__file__)
        .resolve()
        .parents[1]
        / "diff_exporter_hook.py"
    )

    HookHandler(
        file=hook_file,
        base_path=hook_file.parent,
    ).run(
        context,
    )

    return 0



if __name__ == "__main__":
    raise SystemExit(
        main()
    )