name: 📦 Datamodel | Create dumps

concurrency:
  group: dumps-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'workflow_call' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - datamodel/**
      - '.github/workflows/datamodel-dumps-documentation.yml'
  workflow_dispatch:
  workflow_call:
    inputs:
      release_tag:
        required: false
        description: 'Release tag to upload dumps as GitHub Release asset'
        default: ''
        type: string

jobs:
  datamodel-dumps:
    uses: opengisch/oqtopus/.github/workflows/reusable-datamodel-dumps.yml@main
    with:
      pgservice: pg_tww
      db_name: tww
      demo_data: Aletsch
      compose_project_name: wastewater
      release_tag: ${{ inputs.release_tag }}
    secrets: inherit
