name: 📦 Datamodel | Create documentation

concurrency:
  group: dumps-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - datamodel/**
      - '.github/workflows/datamodel-create-documentation.yml'
  workflow_dispatch:
  workflow_call: # Allows this workflow to be called by other workflows
      inputs:
        release_tag:
          required: false
          description: 'Release tag to upload datamodel documentation as GitHub Release asset'
          default: ''
          type: string


jobs:
  datamodel-dumps:
    name: Create datamodel documentation
    runs-on: ubuntu-24.04
    env:
      COMPOSE_PROFILES: schemaspy
      COMPOSE_PROJECT_NAME: wastewater-${{ matrix.extension }}

    strategy:
      matrix:
        extension: ["", "agxx"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Docker build
        run: docker compose up -d --build

      - name: Initialize container
        run: |
          until docker compose exec db pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          docker compose exec db createdb -U postgres tww
          docker compose exec db pum -vvv -s pg_tww -d datamodel install -p SRID 2056 -p modification_agxx ${{ matrix.extension != '' && 'true' || 'false' }} --roles --grant

      - name: Schemaspy
        if: ${{ matrix.extension == '' }}
        run:  docker compose up schemaspy

      - name: Docker logs
        if: failure()
        run: docker compose logs db

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.extension == '' }}
        with:
          name: datamodel-schemaspy
          path: datamodel/schemaspy/
          if-no-files-found: error

      - name: Zip schemaspy output
        run: zip -r datamodel-schemaspy${{ matrix.extension != '' && format('_{0}', matrix.extension) || matrix.extension }}.zip datamodel/schemaspy

      - name: Upload datamodel documentation as GitHub Release asset
        if: ${{ inputs.release_tag != '' }}
        run: |
          if [ -z "${{ matrix.extension }}" ]; then
            gh release upload "${{ inputs.release_tag }}" datamodel-schemaspy.zip --repo "$GITHUB_REPOSITORY"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
