name: 🔌 Plugin | Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - datamodel/**
      - plugin/**
      - '.github/workflows/plugin-test.yml'
  pull_request:
    branches:
      - main
    paths:
      - datamodel/**
      - plugin/**
      - '.github/workflows/plugin-test.yml'
  workflow_dispatch:


jobs:
  plugin-tests:
    name: Run unit tests on plugin
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        qgis_version: [stable-noble, latest]
    env:
      PGSERVICE: pg_tww
      DB_NAME: tww
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
      COMPOSE_PROFILES: qgis

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup env
        run: cp .env.example .env

      - name: Download Interlis libs
        run: sudo ./plugin/scripts/download-interlis-libs.sh

      - name: Docker build
        run: docker compose --profile qgis up --build -d

      - name: Clear Database
        run: |
          until docker compose exec db pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          # create the database
          docker compose exec db sh -c "createdb -U postgres ${DB_NAME}"
          docker compose run pum -p ${PGSERVICE} -d datamodel install -p SRID 2056

      - name: Test on QGIS
        run: docker compose exec qgis /usr/src/plugin/.docker/run-docker-tests.sh --deselect teksi_wastewater/tests/test_interlis.py::TestInterlis::test_dss_dataset_import_export

      - name: Clear Database
        run: |
          docker compose exec db sh -c "dropdb -U postgres ${DB_NAME}"
          docker compose exec db sh -c "createdb -U postgres ${DB_NAME}"
          docker compose run pum -p ${PGSERVICE} -d datamodel install -p SRID 2056

      - name: Test on QGIS DSS dataset
        run: docker compose exec qgis /usr/src/plugin/.docker/run-docker-tests.sh teksi_wastewater/tests/test_interlis.py::TestInterlis::test_dss_dataset_import_export

      - name: Clear Database
        run: |
          docker compose exec db sh -c "dropdb -U postgres ${DB_NAME}"
          docker compose exec db sh -c "createdb -U postgres ${DB_NAME}"
          docker compose run pum -p ${PGSERVICE} -d datamodel install -p SRID 2056

      - name: Run pytest (QGIS)
        run: |
          docker compose exec qgis pytest /usr/src/plugin/tests -m qgis -v

      - name: docker logs
        run: docker compose logs db

  plugin-tests-no-qgis:
    name: Tests (no QGIS)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup env
        run: cp .env.example .env

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r plugin/teksi_wastewater/requirements.txt

      - name: Download Interlis libs
        run: sudo ./plugin/scripts/download-interlis-libs.sh

      - name: Start DB
        run: docker compose up db -d

      - name: Wait for DB
        run: |
          until docker compose exec db pg_isready -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Init DB
        run: |
          docker compose exec db sh -c "createdb -U postgres ${DB_NAME}"
          docker compose run pum -p ${PGSERVICE} -d datamodel install -p SRID 2056

      - name: Run pytest (no QGIS)
        run: pytest -m no_qgis -v
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Show logs
        run: docker compose logs db
